---
title: "第 2 章"
author: "Jin"
date: '2019-04-15'
institute: 中南财经政法大学统计与数学学院
csl: ./style/chinese-gb7714-2005-numeric.csl
css: ./style/markdown.css
bibliography: [./Bibfile.bib]
notice: '@*'
eqnPrefixTemplate: ($$i$$)
link-citations: true
linkReferences: true
chapters: true
tableEqns: false
autoEqnLabels: false
classoption: "aspectratio=1610"
---

```{r setup, echo=F, purl=F}

################# 第 2 章 R 程序代码  ####################

knitr::opts_knit$set(root.dir = getwd())
knitr::opts_chunk$set(echo = FALSE, results = 'hide')
knitr::opts_chunk$set(warning = FALSE, message=FALSE)
knitr::opts_chunk$set(fig.align="center"
                      ## ,out.width="0.9\\textwidth" # latex
                      ,out.width="60%" # for both latex and html
                      ,fig.width=5, fig.height=3
                      )
```

```{r prepare, echo=F, purl=F}
rm(list=ls())
options(digits=4)
options(scipen=100)
graphics.off()
Sys.setlocale("LC_ALL", "Chinese")
```



# 黄金期货市场及价格波动风险研究基础

## 黄金期货市场风险的影响因素

黄金期货市场属于金融资本交易场所，则意味着当取得投资回报时，也存在一定的市场风险。其风
险大致包含市价波动、流动性、市场信用、公开操作和法律方面。从而针对不同种类的风险，
就对应着不一样的影响因素。



<!-- # 参考文献 {-} -->
<!--[//]: # (\bibliography{Bibfile})-->
	
