---
title: "第 4 章"
author: "Jin"
date: '2019-04-15'
institute: 中南财经政法大学统计与数学学院
csl: ./style/chinese-gb7714-2015-numeric.csl
css: ./style/markdown.css
bibliography: [./Bibfile.bib]
notice: '@*'
eqnPrefixTemplate: ($$i$$)
link-citations: true
linkReferences: true
chapters: true
tableEqns: false
autoEqnLabels: false
classoption: "aspectratio=1610"
---

```{r setup, echo=F, purl=F}

################# 第 4 章 R 程序代码  ####################

knitr::opts_knit$set(root.dir = getwd())
knitr::opts_chunk$set(echo = FALSE, results = 'hide')
knitr::opts_chunk$set(warning = FALSE, message=FALSE)
knitr::opts_chunk$set(fig.align="center"
                      ## ,out.width="0.9\\textwidth" # latex
                      ,out.width="60%" # for both latex and html
                      ,fig.width=5, fig.height=3
                      )
```

```{r prepare, echo=F, purl=F}
rm(list=ls())
options(digits=4)
options(scipen=100)
graphics.off()
Sys.setlocale("LC_ALL", "Chinese")
```
# 基于 GAS 模型的黄金期货市场风险测度研究

## 基于 GAS 模型的黄金期货风险测度

### VaR 滚动预测

为了对同业拆借市场的利率风险进行控制，可以借助“风险价值”（Value-at-Risk，VaR）来进行准
确测度。在险价值表示`_lfun`在某个置信水平下，由于市场的正常波动，金融资产的预计最大损失，
即收益率密度曲线的一个分位点。若 $VaR>r_t$，则说明该模型在第t天具备优良的表现，可以成
功预测。


<!--# 参考文献 {-}-->
[//]: # (\bibliography{Bibfile})
	
